packageExtensions:
  foundry-vtt-types@*:
    dependencies:
      "@pixi/constants": 6.0.4
      "@pixi/core": 6.0.4
      "@pixi/display": 6.0.4
      "@pixi/graphics": 6.0.4
      "@pixi/math": 6.0.4
      "@pixi/runner": 6.0.4
      "@pixi/settings": 6.0.4
      "@pixi/sprite": 6.0.4
      "@pixi/ticker": 6.0.4
      "@pixi/utils": 6.0.4

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
